apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "symbolapi.fullname" . }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "symbolapi.fullname" . }}
            port:
              number: {{ .Values.service.port }}